# doxygen and g++-4.9 install trick taken from
# https://amodernstory.com/2015/07/27/upgrading-travisci-build-scripts/
language: cpp
compiler:
# - clang
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports 
    packages:
      - doxygen
      - g++-4.9
      - libgsl0-dev
script:
  - cd build
  - make CXX=g++-4.9
after_success:
  - cd ..
  - doxygen
  - bash deploy.sh
